// Regenerates pure.js from index.html so the logic tests can never silently
// run against a stale copy. Run this before logic.test.js.
import fs from 'fs';
const src = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const js = src.slice(src.lastIndexOf('<script>') + 8, src.lastIndexOf('</script>'));
const names = ['wordStamp','mergeCloud','hasStreak','mergeStreak','localDayIndex','monthKey',
  'grantMonthlyFreeze','levenshtein','weightedSample','norm',
  'nickLen','clean','migrateWord','rankRows','withRanks','boardNum','fmtNum','nickNorm','nickIssue','pkgById','pkgReady','pkgWords','regionOn','wordAllowed','pkgProgressPct','shuffle','markOf','spellDiff','spellWords','wordsToPush','tombsToPush'];
const out = [];
for (const n of names) {
  const m = new RegExp('\\nfunction ' + n + '\\(').exec(js);
  if (!m) { console.error('MISSING from index.html: ' + n); process.exit(1); }
  const start = m.index + 1;
  let i = js.indexOf('{', start), d = 0;
  for (let k = i; k < js.length; k++) {
    if (js[k] === '{') d++;
    else if (js[k] === '}' && --d === 0) { out.push(js.slice(start, k + 1)); break; }
  }
}
// Constants these functions close over, copied from index.html so a change
// there shows up here instead of being quietly mocked.
const DAY = /const DAY=(\d+)/.exec(js)[1];
const INTERVALS = /const INTERVALS=(\[[^\]]*\])/.exec(js)[1];
const grab = n => { const m = new RegExp('const ' + n + '=([\\s\\S]*?);\\n').exec(js); if(!m){console.error('MISSING const: '+n);process.exit(1);} return m[1]; };
const MARKS = /const MARKS=(\[[^\]]*\])/.exec(js)[1];
const PKGSTATE = 'let PKGDB={};let PACKAGES=[];let PKGW={};'
  // pkgProgressPct now asks wordAllowed what the reader can actually see, and
  // wordAllowed reads the settings. Give the tests the real functions and a real
  // settings object rather than mocking the filter away -- the filtered
  // percentage is exactly the part worth testing.
  + 'let _S={explicit:false,regions:{all:true,us:true,uk:true,au:true}};function S(){return _S;}';
const LISTS = ['LEET','NICK_BAN','NICK_BAN_WORD','NICK_BAN_WHOLE','NICK_INVISIBLE'].map(n => 'const ' + n + '=' + grab(n) + ';').join('\n');
fs.writeFileSync(new URL('./pure.js', import.meta.url),
  '// GENERATED by extract.mjs -- do not edit. Run: node extract.mjs\n' +
  'const DAY=' + DAY + ';\nconst INTERVALS=' + INTERVALS + ';\nconst MARKS=' + MARKS + ';\n' + LISTS + '\n' + PKGSTATE + '\n' +
  'let _ga=[];function gaEvent(n,p){_ga.push(n);}\n' +
  out.join('\n') + '\nmodule.exports={DAY,INTERVALS,MARKS,' + names.join(',') + ',__setPkg,__setSettings};\n'
  + 'function __setPkg(c,p,w){PACKAGES.length=0;c.forEach(x=>PACKAGES.push(x));Object.keys(PKGDB).forEach(k=>delete PKGDB[k]);Object.assign(PKGDB,p);Object.keys(PKGW).forEach(k=>delete PKGW[k]);if(w)Object.assign(PKGW,w);}\n'
  + 'function __setSettings(o){_S=Object.assign({explicit:false,regions:{all:true,us:true,uk:true,au:true}},o||{});}\n');
console.log('extracted ' + out.length + ' functions, INTERVALS=' + INTERVALS);
