// Regenerates pure.js from index.html so the logic tests can never silently
// run against a stale copy. Run this before logic.test.js.
import fs from 'fs';
const src = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const js = src.slice(src.lastIndexOf('<script>') + 8, src.lastIndexOf('</script>'));
const names = ['wordStamp','mergeCloud','hasStreak','mergeStreak','localDayIndex','monthKey',
  'grantMonthlyFreeze','levenshtein','weightedSample','norm',
  'nickLen','clean','migrateWord'];
const out = [];
for (const n of names) {
  const m = new RegExp('\\nfunction ' + n + '\\(').exec(js);
  if (!m) { console.error('MISSING from index.html: ' + n); process.exit(1); }
  const start = m.index + 1;
  let i = js.indexOf('{', start), d = 0;
  for (let k = i; k < js.length; k++) {
    if (js[k] === '{') d++;
    else if (js[k] === '}' && --d === 0) { out.push(js.slice(start, k + 1)); break; }
  }
}
// Constants these functions close over, copied from index.html so a change
// there shows up here instead of being quietly mocked.
const DAY = /const DAY=(\d+)/.exec(js)[1];
const INTERVALS = /const INTERVALS=(\[[^\]]*\])/.exec(js)[1];
fs.writeFileSync(new URL('./pure.js', import.meta.url),
  '// GENERATED by extract.mjs -- do not edit. Run: node extract.mjs\n' +
  'const DAY=' + DAY + ';\nconst INTERVALS=' + INTERVALS + ';\n' +
  'let _ga=[];function gaEvent(n,p){_ga.push(n);}\n' +
  out.join('\n') + '\nmodule.exports={DAY,INTERVALS,' + names.join(',') + '};\n');
console.log('extracted ' + out.length + ' functions, INTERVALS=' + INTERVALS);
