// GENERATED by extract.mjs -- do not edit. Run: node extract.mjs
const DAY=86400000;
const INTERVALS=[1,3,5,7,14,20,30,60,90];
let _ga=[];function gaEvent(n,p){_ga.push(n);}
function wordStamp(w){return (w&&(w.updatedAt||w.added))||0;}
function mergeCloud(localWords,localTombs,remoteWords,remoteTombs){
  const byId=new Map();
  (localWords||[]).forEach(w=>byId.set(w.id,w));
  (remoteWords||[]).forEach(w=>{
    const cur=byId.get(w.id);
    if(!cur||wordStamp(w)>wordStamp(cur))byId.set(w.id,w);
  });
  const tombs={...(localTombs||{})};
  Object.keys(remoteTombs||{}).forEach(id=>{
    const ts=remoteTombs[id];
    if(!tombs[id]||ts>tombs[id])tombs[id]=ts;
  });
  const words=[];
  byId.forEach((w,id)=>{
    const t=tombs[id];
    if(t&&t>=wordStamp(w))return;
    words.push(w);
  });
  words.sort((a,b)=>(b.added||0)-(a.added||0));
  return {words,tombs};
}
function hasStreak(s){return !!(s&&(s.lastActiveDate||s.current||s.longest));}
function mergeStreak(a,b){
  // One side having no streak record at all is not the same as it reporting
  // zero: merging field-wise against an empty object would hand back min()
  // of a real value and 0, silently spending the user's freezes.
  if(!hasStreak(a))return b&&hasStreak(b)?b:(a||b||{});
  if(!hasStreak(b))return a;
  a=a||{};b=b||{};
  const newer=(b.lastActiveDate||0)>(a.lastActiveDate||0)?b:a;
  return {...newer,
    longest:Math.max(a.longest||0,b.longest||0),
    freezesAvailable:Math.min(a.freezesAvailable||0,b.freezesAvailable||0)};
}
function localDayIndex(ts){
  const d=new Date(ts);
  return Math.floor(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())/DAY);
}
function monthKey(ts){const d=new Date(ts);return d.getFullYear()+'-'+d.getMonth();}
function grantMonthlyFreeze(st){
  const mk=monthKey(Date.now());
  if(st.freezeMonthGranted==null){st.freezeMonthGranted=mk;return;} // first run: don't double-grant on top of the starting stock
  if(st.freezeMonthGranted!==mk){
    st.freezesAvailable=Math.min(2,(st.freezesAvailable||0)+1);
    st.freezeMonthGranted=mk;
  }
}
function levenshtein(a,b){
  a=a||'';b=b||'';
  const m=a.length,n=b.length;
  if(!m)return n;
  if(!n)return m;
  let prev=Array.from({length:n+1},(_,i)=>i);
  for(let i=1;i<=m;i++){
    const cur=[i];
    for(let j=1;j<=n;j++){
      cur[j]=a[i-1]===b[j-1]?prev[j-1]:1+Math.min(prev[j-1],prev[j],cur[j-1]);
    }
    prev=cur;
  }
  return prev[n];
}
function weightedSample(items,weights,n){
  const pool=items.map((it,i)=>({it,w:weights[i]}));
  const picked=[];
  for(let k=0;k<n&&pool.length;k++){
    const total=pool.reduce((s,p)=>s+p.w,0);
    let r=Math.random()*total,idx=0;
    for(;idx<pool.length-1;idx++){r-=pool[idx].w;if(r<=0)break;}
    picked.push(pool[idx].it);
    pool.splice(idx,1);
  }
  return picked;
}
function norm(s){
  return (s||'').toLowerCase().normalize('NFKC')
    .replace(/[^\p{L}\p{N}\s]/gu,' ')
    .replace(/\s+/g,' ').trim();
}
function foldMarks(s){return (s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').normalize('NFC');}
function typoOk(a,tg){
  const n=tg.length;
  if(n<5)return false;
  // A slip keeps the length about the same -- a transposition is identical,
  // a dropped or doubled character is off by one. Two whole characters added
  // is not a typo, it is a different word: "unimportant" is two edits from
  // "important" and means the opposite.
  if(Math.abs(a.length-n)>1)return false;
  return levenshtein(a,tg)<=(n>=8?2:1);
}
function closeEnough(ans,target,w,showEng){
  const a=foldMarks(norm(ans)), tg=foldMarks(norm(target));
  if(!a)return false;
  if(a===tg)return true;
  // Containment only counts when the answer is a substantial part of the
  // target. With no length floor, a single character that happened to appear
  // in the answer graded as CORRECT ("a" for "important"), which is not just
  // a free pass -- it pushed the word out to a longer interval.
  const lo=Math.min(a.length,tg.length), hi=Math.max(a.length,tg.length);
  if(lo>=2&&lo/hi>=0.6){
    // Answer is part of the target: a partial but substantial answer.
    if(tg.includes(a))return true;
    // Answer is the target plus extra. Only credit a trailing inflection --
    // extra at the FRONT is usually a negation ("unimportant" for
    // "important", "неважный" for "важный"), which is the opposite meaning
    // and must not be graded correct.
    if(a.startsWith(tg))return true;
  }
  if(typoOk(a,tg))return true;
  if(!showEng){
    const wn=foldMarks(norm(w.word));
    return wn===a||typoOk(a,wn);
  }
  const bag=new Set();
  foldMarks(norm((w.ja||'')+' '+(w.meanings||[]).map(m=>m.defJa||m.def).join(' ')))
    .split(' ').forEach(x=>{if(x.length>1)bag.add(x);});
  const aw=a.split(' ').filter(x=>x.length>1);
  if(!aw.length)return false;
  const hit=aw.filter(x=>bag.has(x)||[...bag].some(b=>b.includes(x)||x.includes(b))).length;
  return hit/aw.length>=0.5;
}
function nickLen(n){return Array.from(n||'').length;}
function clean(o){return JSON.parse(JSON.stringify(o===undefined?null:o));}
function migrateWord(w){
  // Number.isFinite rather than typeof: NaN and Infinity are both numbers, so
  // a typeof check let them through. A NaN box makes INTERVALS[box] undefined,
  // which makes the next due date NaN, which is never <= now -- the word
  // silently drops out of review forever and no amount of answering brings it
  // back. Clamping the box also keeps a corrupt value from doing the same.
  const num=(v,d)=>Number.isFinite(v)?v:d;
  w.box=Math.max(-1,Math.min(num(w.box,-1),INTERVALS.length-1));
  w.added=num(w.added,Date.now());
  w.updatedAt=num(w.updatedAt,w.added);
  w.nextDue=num(w.nextDue,w.added);
  if(!Array.isArray(w.hist))w.hist=[];
  if(!Array.isArray(w.examples))w.examples=[];
  return w;
}
module.exports={DAY,INTERVALS,wordStamp,mergeCloud,hasStreak,mergeStreak,localDayIndex,monthKey,grantMonthlyFreeze,levenshtein,weightedSample,norm,foldMarks,typoOk,closeEnough,nickLen,clean,migrateWord};
